# Generated by Django 3.1.6 on 2021-02-12 10:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='To',
        ),
        migrations.AlterField(
            model_name='event',
            name='correlation_id',
            field=models.UUIDField(default=uuid.UUID('4b581f8a-4f2a-4475-b04d-c56ff599491f'), unique=True),
        ),
    ]
