# Generated by Django 3.1.6 on 2021-02-19 08:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210212_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtransfer',
            name='total',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='event',
            name='correlation_id',
            field=models.UUIDField(default=uuid.UUID('725e4e87-d2ce-4ad2-abe4-b22646b6c9a2'), unique=True),
        ),
    ]
