# Generated by Django 3.1.6 on 2021-03-19 10:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210219_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='correlation_id',
            field=models.UUIDField(default=uuid.UUID('9c0a9942-59bc-4f97-bb22-98cda0be38fd'), unique=True),
        ),
        migrations.CreateModel(
            name='UsersPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.useraccount')),
            ],
            options={
                'unique_together': {('user', 'item')},
            },
        ),
    ]
